# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0'

# CI
gem 'rubocop', require: false

# data structure
gem 'dry-types'
gem 'dry-struct'

group :test, :development do
  # debug
  gem 'byebug'
end

group :test do
  gem 'rspec'
end
