require_relative 'commands/command_invoker'
require_relative 'commands/base_command'
require_relative 'commands/replenish_balance_command'
require_relative 'commands/open_investment_command'
require_relative 'commands/close_investment_command'
require_relative 'commands/add_dividend_command'
