source 'https://rubygems.org'

ruby '3.0.1'

gem 'roda'

# servers
gem 'puma'

# views
gem 'erubi'
gem 'tilt'

# database
gem 'pg'
gem 'sequel'

# config
gem 'dotenv'
gem 'rake'

# debug
gem 'byebug'

# CI
gem 'rubocop', require: false

# test
group :test do
  gem 'cucumber'
  gem 'rspec'
  gem 'rspec-roda'
end
